### ISSUE TITLE
[Bug]: Valve tank built into ground empties contents on world load

### ISSUE THREAD

**Issue by Scironex** [Soaryn/XyCraftTracker#36] opened 2024-01-15 13:10 UTC
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

A tank built by digging a cuboid into the ground and placing a valve on top seems to delete its contents whenever the world is reloaded. I don't believe it deletes its contents if it's loaded again in the same session, i.e. if the player moves far enough away that the chunk unloads, then returns. However, this is an observation purely based off of the fact that I hadn't noticed anything lost after exploration.

### Reproduction Steps

Hollow out a cuboid into the ground.
Cover the top layer with valid tank side blocks.
Place a valve along that side and right click it to form the multiblock.
Fill the tank with an amount of fluid.
Exit the world and load back in.

### Screenshots and Videos

![2024-01-15_06 36 45](https://github.com/Soaryn/XyCraftTracker/assets/33199757/f3e48ff0-520d-44eb-b418-d811ce6ac2b4)

### Additional Context

The tank in question was 9x9x9 internal, 11x11x11 external. The setup in the screenshot was being filled with pipes from the Create mod. All sides and edges were made of various colors of Terracotta blocks, except the top, which was Xycraft Glass Viewers. The majority of the Terracotta blocks used in the tank were naturally generated - That is, they were present on world generation, rather than being placed by the player.

Tanks built with similar materials in a similar configuration, but above ground, did not have the issue; They retained their contents on a world load. Specifically, I built a 9x9x9 internal tank using uncolored Terracotta, but made the top face out of Glass Viewers, and placed the valve in the same orientation.

**Comment by Soaryn** [comment] 2024-01-15 19:45
I've actually noticed this happening in my 1.20.4 dev env, so trying to isllate that this week. We are in the process of changing it over to a new data storage format, so Im confident it will resolve that issue, but to be transparent with the problem
1. I'm not entirely certain what is causing it specifically
2. What ever fix that is devised is unlikely to make it back to an older version with the current scheduling. 

Would you happen to have a picture of the setup so I can see if your test case can be added to ours?

**Comment by Soaryn** [comment] 2024-01-15 19:46
Curiously, could you try addijg a few valves to the other sides to see if the issue persists?

**Comment by Scironex** [comment] 2024-01-15 20:46
Unfortunately, the setup where I encountered the bug was in a survival world, and I had since moved the tank to a location where it wasn't bugging out. When I attempted to recreate the original setup, both in the same location and in a new creative world, the bug did not occur again.

I also searched through the backups folder to see if there was a save from before I moved the tank, but unfortunately, there was not. Should the bug crop up again, I'll let you know and keep a copy of the save at that point.

**Comment by Soaryn** [comment] 2024-01-15 20:48
No worries! This one is a tricky one as I have seen it happen in dev, and have YET to find the root cause. Nor am I able to reliably replicate it yet.

**Comment by nikita488** [comment] 2024-01-15 20:59
So here is the steps that got me to this bug:
1. Form a tank (for the first time)
2. Fill with some fluid and remember last value (500 mb of Water as an example)
3. Close world
4. Open world again
5. Continue to fill it with fluid, then remember the value (2000 mb of Water)
6. Close world
7. Open world again
8. Fluid value will be reseted to first time saved value (500 mb of Water)
9. Break any tank block (except Valve) to unform it
10. Right click on Valve to reform again
11. Now this fluid value fill be always saved/loaded until reforming again

This happens because it seems MultiTank#save(CompoundTag tag) (SavedData method override) method is not always called when data needs to be saved (so like fluid fill/drain etc) using setDirty() (SavedData method).
So after world is saved, the new data will not be saved, and on world load it will load previosly stored SavedData from *world name folder*/data/xycraft_machines/multi_tank/

If only Github allowed me to upload my test world lol (25 mb limit)

**Comment by Soaryn** [comment] 2024-01-15 21:03
Right, so the attachment system vs SavedData will likely be a valid fix, but still will be a 1.20.4+ fix. We'll have to see. Doing that in my test world didn't result in any unexpected behavior though the tank I did have that did it fixed magically.

**Comment by nikita488** [comment] 2024-01-15 21:14
Test world for 1.20.1: [TankBugTest.zip](https://github.com/Soaryn/XyCraftTracker/files/13943048/TankBugTest.zip)
I guess attachment system might have something for marking data for saving too

**Comment by Soaryn** [comment] 2024-02-07 09:59
[FIXED]
In theory this has been fixed in dev 1.20.4+ now. I'm closing this, but if you experience it again in the next major update feel free to reopen this issue! Because of how the fix is implemented, 1.20.1 will not be receiving any more fixes as it requires Neo Forge changes that happened in 1.20.3. While technically there is a solution with how we managed data before, it is unfortunately not a great return of time investment :(

**Closed by Soaryn** 2024-02-07 09:59 UTC
Labels: bug, investigating
