### ISSUE TITLE
[Bug-Maybe?]: Dragon Egg isn't extracted

### ISSUE THREAD

**Issue by Pontiac76** [Soaryn/XyCraftTracker#35] opened 2023-12-27 17:22 UTC
### XyCraft Module

Machines

### Minecraft Version

1.20.1

### Severity

Odd Results

### Describe the Suggestion

Right up front, I don't know if this is a Xycraft bug, or if it's a config situation and I need to go to the DW pack maintainers.

I'm playing in the DW 1.20 pack, and I've looked in the configs to see if there's anything relevant to this particular function being disabled, but, it seems as though I'm either doing something wrong, or this particular mechanic is disabled somewhere, somehow.  I'm not seeing anything relevant to to the extractor in the configs in the xycraft directory.

I initially tried placing the egg in the mining dimension, no go, but that's OK.  I then moved it over to The End, and still no-go.  See screen shots.

I am playing on a private server on my LAN, not exposed to the internet.  It's running the 1.10 version of the pack.

### Reproduction Steps

Plop dragon egg down
Plop the extractor on top of the egg
Put storage on top
Expected to see the extractor turn on, or at least stay solid due to invalid inventory on top.

### Screenshots and Videos

![image](https://github.com/Soaryn/XyCraftTracker/assets/4532020/d91e9a14-9ac7-4555-8243-b94ee71f70d7)

![image](https://github.com/Soaryn/XyCraftTracker/assets/4532020/d83a3a5c-f39c-4c78-823b-c4f94cbb30e6)

### Additional Context

Note that I have other extractors running, specifically the dragon head, and it's working in the mining dimension without issue.

EDIT: Another thing to note is that the extractor does answer to redstone signals.  The bars turn red to indicate that it's at least being SEEN by the MC engine magic smoke stuffs

**Comment by Pontiac76** [comment] 2023-12-27 17:46
Not sure what this was about, but, thanks to #32 I found that if I put the egg on TOP of the extractor, and pointed it downwards into the chest, this worked.  Is that by design?  Does the green block in my screenshot represent where the output/chest is to go?

My GUESS is yes with this shot:
![image](https://github.com/Soaryn/XyCraftTracker/assets/4532020/4e4c2020-918c-4aca-a8dd-6b05d2a23485)

Comparing to what 32 shows and what this shot shows, it's how I concluded I was doing this upside down.

**Comment by Soaryn** [comment] 2023-12-28 11:46
I definitely admit it is unclear, and I am hopefully able to get around to a better visual, the green block represents the vslide side of the "target" block the extractor can go. 

The hope is to make orientation based rules show in a cycling manner, but there wasnt a good way to represent some of them quickly.

**Comment by Pontiac76** [comment] 2023-12-28 16:24
I would go as far as if you were to change the word "Orientation" to "Output Direction", it'd make things a bit more clear.

**Comment by Soaryn** [comment] 2024-01-15 20:51
While this is still a UX layer I'd like to address in the future, I am closing this as it not a bug, it is just an odd explanation on my part. 😄

**Closed by Soaryn** 2024-01-15 20:51 UTC
Labels: question
