### ISSUE TITLE
[Bug]: xychorium ore textures not being seamless

### ISSUE THREAD

**Issue by Zurkie** [Soaryn/XyCraftTracker#69] opened 2024-10-21 13:32 UTC
### Mod Title

XyCraft World

### Minecraft Version

1.21.0

### Severity

Odd Results

### NeoForge Version

21.1.71

### Describe the Suggestion

I wondered why the xychorium ore looks out of place a lot of the time (as seen in image) and if this is a bug or some unavoidable thing. This is true for all colors and also deepslate versions. Would be nice if the textures were more seamlessly integrated into their surroundings

### Reproduction Steps

Just natural generation.

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/d46020ba-95fa-42a8-a4d7-185396df9b5d)

**Comment by Soaryn** [comment] 2024-10-28 10:16
That looks to be some "performance improvement" mod causing that lighting to fail. This is now how it looks in my dev environment or on Forgecraft when it was up :( So something else is playing games with the rendering and wildly assuming things it would appear.

**Comment by Zurkie** [comment] 2024-10-28 14:06
So I was able to find the cause of the issue - it was due to using Direwolf's night vision in Just Dire Things while having Sodium installed. Funnily enough, the newest Sodium version that just got released today manages to fix this issue :)

**Comment by Soaryn** [comment] 2024-10-28 21:06
Oh wonderful! Glad that it was resolved :D Sodium tends to have a hit or miss on feature sets Minecraft provides natively, so not surprise it was mostly the cause, but happy to hear that it is no longer an issue.

Hope you have fun! I'll go ahead and close this issue now. 😊

**Closed by Soaryn** 2024-10-28 21:06 UTC
Labels: bug
